#POST http://localhost:8083/order
#Content-Type: application/json
#
#{
#  "product": "coffee",
#  "qty": 1
#}
#
#> {%
#    client.global.set("orderId", response.body.id);
#%}
#
####


POST http://localhost:8083/order
Content-Type: application/json

{
  "product": "coffee",
  "qty": 2,
  "mobileNumber": "+49 176 5546782"
}

> {%
    client.global.set("orderId", response.body.id);
%}

###

POST http://localhost:8083/order/{{orderId}}/payment
Content-Type: application/json

{
  "amountGiven": 3
}

### spring-cloud-contract-stubrunner-boot

GET http://localhost:8085/stubs
GET http://localhost:8085/triggers